### ISSUE TITLE
Safe to use the logger?

### ISSUE THREAD

**Issue by nickelser** [celluloid/celluloid-essentials#4]
With 0.17, it seems that the logger is enabled by including `Celluloid::Internals::Logger`, which seems to indicate it's a private API. Is this safe to still use for actors?

**Comment by digitalextremist** [comment]
Yes, it is safe to use. It was taken out of scope because other people might want to provide their own logger in the global namespace, which would be overriden by `Celluloid::Logger` if `include 'Celluloid'` were in use.

**Comment by nickelser** [comment]
Makes total sense, thank you.
